### ISSUE TITLE
empty page when clicking on otp users

### ISSUE THREAD

**Issue by sobers-2002** [loki36/user-otp#99]
Have version 2.5 installed with a fresh owncloud 8 setup. 

Read through bug#93 which had similar issue but the fix suggested there doesn't work for me.

Below are the messages in admin log:

[code]
Error 	PHP 	js file not found: script:js/users serverroot:/var/www/localhost at /var/www/localhost/lib/private/template/resourcelocator.php#46 	2015-03-18T17:31:39+00:00
Fatal 	index 	Exception: {"Message":"Unable to generate a URL for the named route \"isadmin\" as such route does not exist.","Code":0,"Trace":"#0 \/var\/www\/localhost\/lib\/private\/route\/router.php(282): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('isadmin', Array, false)\n#1 \/var\/www\/localhost\/lib\/private\/route\/cachingrouter.php(39): OC\\Route\\Router->generate('isadmin', Array, false)\n#2 \/var\/www\/localhost\/lib\/private\/urlgenerator.php(42): OC\\Route\\CachingRouter->generate('isadmin', Array)\n#3 \/var\/www\/localhost\/lib\/private\/helper.php(112): OC\\URLGenerator->linkToRoute('isadmin', Array)\n#4 \/var\/www\/localhost\/apps\/user_otp\/templates\/list_users.php(17): OC_Helper::linkToRoute('isadmin')\n#5 \/var\/www\/localhost\/lib\/private\/template\/base.php(142): include('\/var\/www\/clowde...')\n#6 \/var\/www\/localhost\/lib\/private\/template\/base.php(120): OC\\Template\\Base->load('\/var\/www\/clowde...')\n#7 \/var\/www\/localhost\/lib\/private\/template.php(115): OC\\Template\\Base->fetchPage()\n#8 \/var\/www\/localhost\/lib\/private\/template\/base.php(103): OC_Template->fetchPage()\n#9 \/var\/www\/localhost\/apps\/user_otp\/list_users.php(114): OC\\Template\\Base->printPage()\n#10 \/var\/www\/localhost\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/var\/www\/clowde...')\n#11 [internal function]: __lambda_func(Array)\n#12 \/var\/www\/localhost\/lib\/private\/route\/router.php(250): call_user_func('\\x00lambda_49', Array)\n#13 \/var\/www\/localhost\/lib\/base.php(767): OC\\Route\\Router->match('\/apps\/user_otp\/...')\n#14 \/var\/www\/localhost\/index.php(36): OC::handleRequest()\n#15 {main}","File":"\/var\/www\/localhost\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134} 	2015-03-18T17:31:39+00:00
Error 	PHP 	date_default_timezone_set(): Timezone ID '' is invalid at /var/www/localhost/apps/user_otp/3rdparty/multiotp/multiotp.class.php#3759 	2015-03-18T17:31:39+00:00
Error	PHP	Undefined index: timezone at /var/www/localhost/apps/user_otp/3rdparty/multiotp/multiotp.class.php#3756	2015-03-18T17:31:39+00:00
Error	PHP	Undefined index: display_log at /var/www/localhost/apps/user_otp/3rdparty/multiotp/multiotp.class.php#2504	2015-03-18T17:31:39+00:00
Error	PHP	Undefined index: debug at /var/www/localhost/apps/user_otp/3rdparty/multiotp/multiotp.class.php#2499	2015-03-18T17:31:39+00:00
Error	PHP	Undefined index: log at /var/www/localhost/apps/user_otp/3rdparty/multiotp/multiotp.class.php#2494	2015-03-18T17:31:39+00:00
Error	PHP	Undefined index: backend_type_validated at /var/www/localhost/apps/user_otp/3rdparty/multiotp/multiotp.class.php#1996	2015-03-18T17:31:39+00:00
[/code]

didn't know if posting in the previous bug was better so I have just posted a new one

**Comment by GhostPunk** [comment]
this happened to me too, couldn't find the solution yet.
